name: yoboulma_app
description: "Plateforme de livraison groupée du dernier kilomètre pour Dakar"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  # State Management
  provider: ^6.1.2

  # Routing & Navigation
  go_router: ^14.2.0

  # HTTP & API
  http: ^1.2.2
  dio: ^5.4.2+1

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1

  # OTP & Security
  otp: 3.2.0

  # Image Picker
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
