enum Role { ADMIN, VENDEUR, LIVREUR, CLIENT }

enum OrderStatus {
  EN_ATTENTE_DE_LIVREUR,
  PRISE_EN_CHARGE,
  EN_COURS_DE_LIVRAISON,
  ARRIVE_A_DESTINATION,
  LIVREE,
}

enum BatchStatus { DISPONIBLE, PRISE_EN_CHARGE, EN_COURS, TERMINE }
